### ISSUE TITLE
Exception in thread "main" com.sun.tools.javac.util.Abort

### ISSUE THREAD

**Issue by System25** [google/j2objc#1034]
Hello everybody, if you try to compile a class file with an incorrect "package" directive a the begining of the java file, the following error appears:

```
Exception in thread "main" com.sun.tools.javac.util.Abort
	at com.sun.tools.javac.comp.Check.completionError(Check.java:287)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:584)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
	at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:834)
	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:558)
	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449)
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:528)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:316)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:359)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:344)
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:174)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:137)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:67)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:82)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:129)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:178)
```

To reproduce the error just change the package name of any java file:

```
package bad.package.name;

public class Whatever {
}
```

Best regards!

**Comment by tomball** [comment]
Thanks for providing such a clear test for this issue, it really helps! As the stacktrace shows, that issue is with javac. It looks to be fixed in the version of javac built into j2objc-2.3, however:
```
$ ~/j2objc-2.3/j2objc ~/tmp/Whatever.java
/Users/tball/tmp/Whatever.java:1: error: <identifier> expected
package bad.package.name;
            ^
/Users/tball/tmp/Whatever.java:1: error: class, interface, or enum expected
package bad.package.name;
                   ^
/Users/tball/tmp/Whatever.java:1: error: class, interface, or enum expected
package bad.package.name;
                    ^
```
I therefore recommend that you update your system to the [latest version of j2objc](https://github.com/google/j2objc/releases/latest). To verify what version of javac that a j2objc release uses, run the following (after changing the path):
```
$ java -classpath ~/j2objc-2.3/lib/j2objc.jar com.sun.tools.javac.Main -version
javac 1.8.0_191
```

**Comment by tomball** [comment]
I see the latest release is actually 2.3.1, and will verify it also works. If not, I'll reopen this issue and we'll work on a new release with an updated javac.

**Comment by tomball** [comment]
Version 2.3.1 has the same javac version, 1.8.0_191.

**Comment by System25** [comment]
Hi Tom, sorry for the previous example because it wasn't a clear one. It only was meant to let you know that there was a bug. I imagine that you noticed that "bad.package.name" can't be used because "package" is a reserved word. But does it's not the problem.

Ok, let's see a clear example. First of all, let's fix "Whatever" class:

```
package bad.pckg.name;

public class Whatever {
}
```
And not lets define "Other" class that uses "Whatever" class:

```
package good.pckg.name;

import good.pckg.name.Whatever;

public class Other {
}
```

So, the directory structure is this:

```
$ find .
.
./good
./good/pckg
./good/pckg/name
./good/pckg/name/Whatever.java
./good/pckg/name/Other.java
```

Now if you try to compile "Other" class the error appears:

```
$ /Users/myuser/j2objc-2.3.1/j2objc good/pckg/name/Other.java
Exception in thread "main" com.sun.tools.javac.util.Abort
	at com.sun.tools.javac.comp.Check.completionError(Check.java:287)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:584)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
	at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:834)
	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:558)
	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449)
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:528)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:316)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:359)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:344)
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:174)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:137)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:67)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:82)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:129)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:178)
```

Thanks and best regards!

**Comment by tomball** [comment]
Either install the [latest release](https://github.com/google/j2objc/releases/latest), or if you build from source, then ```git pull``` and rebuild:
```
$ cat good/pckg/name/*
package good.pckg.name;

public class Other {
}
package good.pckg.name;

public class Whatever {
}
$ find .
.
./good
./good/pckg
./good/pckg/name
./good/pckg/name/Whatever.java
./good/pckg/name/Other.java
$ ~/j2objc-2.3.1/j2objc good/pckg/name/Other.java
$ find .
.
./good
./good/pckg
./good/pckg/name
./good/pckg/name/Other.h
./good/pckg/name/Whatever.java
./good/pckg/name/Other.m
./good/pckg/name/Other.java
```

**Comment by tomball** [comment]
Also, if you build from source, make sure your Java 8 installation is at least version 1.8.0_191 -- that bug is in javac, and j2objc's build copies in the version that's installed on your system. To check what version is installed, run:
```
$ java -classpath `/usr/libexec/java_home -v 1.8`/lib/tools.jar com.sun.tools.javac.Main -version
```

**Comment by System25** [comment]
> Either install the [latest release](https://github.com/google/j2objc/releases/latest), or if you build from source, then `git pull` and rebuild:
> 
> ```
> $ cat good/pckg/name/*
> package good.pckg.name;
> 
> public class Other {
> }
> package good.pckg.name;
> 
> public class Whatever {
> }
> $ find .
> .
> ./good
> ./good/pckg
> ./good/pckg/name
> ./good/pckg/name/Whatever.java
> ./good/pckg/name/Other.java
> $ ~/j2objc-2.3.1/j2objc good/pckg/name/Other.java
> $ find .
> .
> ./good
> ./good/pckg
> ./good/pckg/name
> ./good/pckg/name/Other.h
> ./good/pckg/name/Whatever.java
> ./good/pckg/name/Other.m
> ./good/pckg/name/Other.java
> ```

Hi Tom, just to be 100% sure, in my example "Whatever" class package name was "bad.pckg.name", and in your example it seems to be "good.pckg.name". To reproduce this error is important that the package name is a wrong package name (but it must not contain the reserved work "package" like in my first example).

Best regards!

**Comment by tomball** [comment]
That's also fixed with the latest release. Just to recap, you found a real bug in the version of javac that was used in an earlier j2objc version, which has been fixed (as far as I can tell) with the latest release and/or building with a JDK 1.8 version >= 1.8.0_191. I'm glad you reported it, as I'm going to add the javac version into j2objc's version string to improve support in the future:
```
$ cat good/pckg/name/Whatever.java
package bad.pckg.name;

public class Whatever {
}
$ ~/j2objc-2.3.1/j2objc good/pckg/name/Other.java
$
```
