### ISSUE TITLE
[BUG] Unable to parse BigDecimal with scientific notation

### ISSUE THREAD

**Issue by tranleduy2000** [google/j2objc#1059]
This test bellow will run infinite, it should throw NumberFormatException
```Swift
    func testJavaBigDecimal() {
        let d = BigDecimal("1234e-2.3");
    }
```

**Comment by antonio-cortes-perez** [comment]
I tried the following test with the J2ObjC release 2.4 and got the expected result:

import java.math.BigDecimal;
public class Example {
  public static void main(String[] args) {
    try {
      new BigDecimal("1234e-2.3");
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}

$ javac Example.java 
$  java Example
java.lang.NumberFormatException
	at java.math.BigDecimal.parseExp(BigDecimal.java:650)
	at java.math.BigDecimal.<init>(BigDecimal.java:491)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:809)
	at Example.main(Example.java:5)

$  ~/j2objc-2.4/j2objc Example.java 
$  ~/j2objc-2.4/j2objcc Example.m
$  ./a.out Example
java.lang.NumberFormatException
	at 0x00000001068d6ad2 java.math.BigDecimal.parseExp() + 519
	at 0x00000001068d660c java.math.BigDecimal.<init>() + 1948
	at 0x0000000106887b88 Example.main() + 24
	at 0x0000000106887b5d Example.main() + 29
	at 0x0000000106b2dff8 java.lang.reflect.Method.invoke:object:() + 22
	at 0x0000000106b2db8e java.lang.reflect.Method.invoke() + 389
