### ISSUE TITLE
Exit code 1, Exit code 130

### ISSUE THREAD

**Issue by ViorelOnica** [google/j2objc#1188]
Hello, I'm dealing with two types of errors (exit code 1 and exit code 130) on two different files.

**Both errors begin with this:**
_RuleScriptExecution 
    <java_file_path> normal arm64
    cd <xcode_project_path>
    [...]_

**Both errors end with this:**
_RuleScriptExecution <java_file_path> normal arm64
    /bin/sh -c if\ [\ !\ -f\ \"${J2OBJC_HOME}/j2objc\"\ ];\ then\ echo\ \"J2OBJC_HOME\ is\ not\ correctly\ defined,\ currently\ set\ to\ \'${J2OBJC_HOME}\'\";\ exit\ 1;\ fi;\
\"${J2OBJC_HOME}/j2objc\"\ -d\ ${DERIVED_FILE_DIR}\ -sourcepath\ \"/Users/viorelonica/Desktop/src\"\ --no-package-directories\ -g\ ${INPUT_FILE_PATH};\_

**And the error statement:**
_Command /bin/sh failed with exit code 1 (or 130)_

**First error (error code 1) throws this exception:**
_Exception in thread "main" com.sun.tools.javac.util.Abort
	at com.sun.tools.javac.comp.Check.completionError(Check.java:287)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:584)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
	at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:834)
	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:558)
	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449)
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:528)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)
	at com.sun.tools.javac.main.JavaCompiler.complete(JavaCompiler.java:785)
	at com.sun.tools.javac.main.JavaCompiler$1.complete(JavaCompiler.java:312)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2535)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2442)
	at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.jvm.ClassReader.loadClass(ClassReader.java:2623)
	at com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:1907)
	at com.sun.tools.javac.comp.Resolve.findGlobalType(Resolve.java:2007)
	at com.sun.tools.javac.comp.Resolve.findType(Resolve.java:2081)
	at com.sun.tools.javac.comp.Resolve.findIdent(Resolve.java:2110)
	at com.sun.tools.javac.comp.Resolve.resolveIdent(Resolve.java:2384)
	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3170)
	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
	at com.sun.tools.javac.comp.Attr.attribBase(Attr.java:786)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1057)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:316)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:359)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:344)
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:198)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:137)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:67)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:82)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:176)
Command /bin/sh failed with exit code 1_

I want to mention that I added org.slf4 library java source files (http://www.slf4j.org) to my main group called **"src"** (check the picture below). Could this be the problem?
<img width="335" alt="Screenshot 2020-01-27 at 15 46 23" src="https://user-images.githubusercontent.com/27728770/73179790-c51b1e80-411c-11ea-93dc-99b1d4fea200.png">

**Comment by tomball** [comment]
All those "com.sun.tools.javac" stackframes means you have a javac error (j2objc runs javac first). The fix for **all** javac-related issues is to not run j2objc until you have a working javac command line command, with correct -source, -sourcepath, and maybe -classpath flags (though paths on the classpath must be separately transpiled for the app to build). Once that builds without errors, then use the same flags with the j2objc command.

Next, only build Java sources in Xcode that you are actively modifying, as Xcode requires each source to be separately compiled and that takes much longer than running a single javac or j2objc command. Since you are not likely to be modifying slf4j:

1. In Xcode, remove the existing MyProjectTest/src/org/slf4j sources from your project.
2. Unzip slf4j-api-1.7.30-sources.jar to a temporary directory (let's call it ~/tmpdir for these instructions).
3. In a command-line window run "j2objc -d MyProjectTest/src -g -sourcepath ~/tmpdir $(find ~/tmpdir -name '*.java')". If this doesn't work, change "j2objc" to "javac" and fix the flags, then switch back.
4. In Xcode, add the .h and .m files in MyProjectTest/src/org/slf4j to the project.
5. If Xcode can't find slf4j headers, add the full path to MyProjectTest/src to the target's Header Search Paths build setting.

In general, building Java sources in Xcode is problematic because even though it supported Java sources ten years ago, with every release they seem to remove more support for languages like it.
