### ISSUE TITLE
upgrade last mac version: macOS Big Sur

### ISSUE THREAD

**Issue by peter100u** [google/j2objc#1521]
Fatal error: Exception in thread "main" java.lang.NullPointerException
	at com.google.devtools.j2objc.javac.JavacParser.getFileManager(JavacParser.java:105)
	at com.google.devtools.j2objc.javac.JavacParser.createEnvironment(JavacParser.java:195)
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:162)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:141)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:70)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:1)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:177)

**Comment by tomball** [comment]
You should upgrade to the latest release of j2objc ([version 2.7](https://github.com/google/j2objc/releases/tag/2.7)), as `JavaParser.getFileManager()` hasn't been at line 105 for years. 

I don't know if that will fix it working on Big Sur since Google hasn't pushed it out to its engineers yet, so I'll leave this open until we can verify it works there.

**Comment by superLiuYiPeng** [comment]
thank you , i want to try it

**Comment by tomball** [comment]
Verified current source builds on Big Sur.
