### ISSUE TITLE
JRE timezone database not accessible compiling with Java 9 or above

### ISSUE THREAD

**Issue by alosoz** [google/j2objc#1632]
package day30_datetime;
import java.time.LocalTime;
public class C2_LocalTime {
    public static void main(String[] args) {
        
        LocalTime saat = LocalTime.now();
        System.out.println(saat);        
    }
}

i get this error messages

can't open C:\Users\Tec Pro\AppData\Local\Temp\eoi1CD3.tmp\plugins\org.eclipse.justj.openjdk.hotspot.jre.minimal.stripped.win32.x86_64_15.0.1.v20201027-0507\jre\lib\tzmappings.
Exception in thread "main" java.lang.Error: java.io.FileNotFoundException: C:\Users\Tec Pro\AppData\Local\Temp\eoi1CD3.tmp\plugins\org.eclipse.justj.openjdk.hotspot.jre.minimal.stripped.win32.x86_64_15.0.1.v20201027-0507\jre\lib\tzdb.dat (The system cannot find the file specified)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(Unknown Source)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.util.calendar.ZoneInfoFile.<clinit>(Unknown Source)
	at java.base/sun.util.calendar.ZoneInfo.getTimeZone(Unknown Source)
	at java.base/java.util.TimeZone.getTimeZone(Unknown Source)
	at java.base/java.util.TimeZone.setDefaultZone(Unknown Source)
	at java.base/java.util.TimeZone.getDefaultRef(Unknown Source)
	at java.base/java.util.TimeZone.getDefault(Unknown Source)
	at java.base/java.time.ZoneId.systemDefault(Unknown Source)
	at java.base/java.time.Clock.systemDefaultZone(Unknown Source)
	at java.base/java.time.LocalTime.now(Unknown Source)
	at day30_datetime.C2_LocalTime.main(C2_LocalTime.java:6)
Caused by: java.io.FileNotFoundException: C:\Users\Tec Pro\AppData\Local\Temp\eoi1CD3.tmp\plugins\org.eclipse.justj.openjdk.hotspot.jre.minimal.stripped.win32.x86_64_15.0.1.v20201027-0507\jre\lib\tzdb.dat (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	... 13 more

**Comment by tomball** [comment]
The tzmappings resource files in the java.base module (Java 9 and above) is not accessible when executing the j2objc binary.

Workaround is to install Java 8 and use that to execute j2objc.

**Comment by tomball** [comment]
FYI, compiling j2objc-generated files requires Mac hardware, due to Apple's iOS SDK license. If you don't have a Mac, there's therefore no point in using j2objc.

**Comment by tomball** [comment]
Another workaround is to use [j2objc-2.7](https://github.com/google/j2objc/releases/tag/2.7) with either Java 1.8 or 11.

**Comment by tomball** [comment]
After building from the latest source, I was able to compile your example with Java 15 and Java 11 without issue. We're planning a 2.8 release in the next couple of weeks.
