### ISSUE TITLE
Exception using j2objc2.8 and j2objc2.7 and macOS Moneterey 12.5.1

### ISSUE THREAD

**Issue by Mustafa-Merza** [google/j2objc#1930]
I wanted to test the library to convert a simple java class to objective-c like in the link https://developers.google.com/j2objc/guides/getting-started
but failed to do that in both version 2.7 version and 2.8 and I'm not sure if I did something wrong.

I downloaded the files from [j2objc-2.8.zip](https://github.com/google/j2objc/releases/download/2.8/j2objc-2.8.zip) and [j2objc-2.8-frameworks.zip](https://github.com/google/j2objc/releases/download/2.8/j2objc-2.8-frameworks.zip)
then i added Java jre-8u341-macosx-x64 from oracle

And finally added the paths to both j2objc and java to my PATH variable in zsh shell

And when i tried with the test file Hello.java
```Java
public class Hello {
  public static void main(String[] args) {
    System.out.println("hello, world");
  }
}
```

It gave me this exception

Exception in thread "main" java.lang.NullPointerException
	at com.google.devtools.j2objc.javac.JavacParser.getFileManager(JavacParser.java:129)
	at com.google.devtools.j2objc.javac.JavacParser.createEnvironment(JavacParser.java:255)
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:192)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:137)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:67)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:83)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:176)

**Comment by tomball** [comment]
You need to install the JDK (Java Developer Kit) version of Java 1.8, not
just the 1.8 runtime (JRE). The exception is caused by the Java compiler,
javac, not being installed. The j2objc translator requires javac.

To verify that you have installed the JDK, run ‘javac -version’. To verify
your source files don’t have Java errors, run ‘javac Hello.java’.

**Comment by Mustafa-Merza** [comment]
Thank you for your reply.

I didn't notice that I installed only JRE and not the full JDK.

I have installed JDK 15.0.2 and tried the library and it worked

**Thanks.**
