### ISSUE TITLE
Annotation types cannot be used as default values for other Annotations

### ISSUE THREAD

**Issue by harrycheung** [google/j2objc#470]
This was mentioned on the mailing list today, but I don't see the issue here to I'm posting how to recreate it:
```
// SimpleAnnotate.java
import java.lang.annotation.Target;
import java.lang.annotation.Retention;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Target({TYPE, METHOD, FIELD}) 
@Retention(RUNTIME)
public @interface SimpleAnnotate {
    String value() default "default_value";
}
```
```
// ComplexAnnotate.java
import java.lang.annotation.Target;
import java.lang.annotation.Retention;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Target({TYPE, METHOD, FIELD}) 
@Retention(RUNTIME)
public @interface ComplexAnnotate {
    SimpleAnnotate anAttribute() default @SimpleAnnotate;
}
```
<code>ComplexAnnotate</code> will fail translation with:
```
Exception in thread "main" java.lang.ClassCastException: com.google.devtools.j2objc.ast.MarkerAnnotation cannot be cast to com.google.devtools.j2objc.ast.Expression
	at com.google.devtools.j2objc.ast.AnnotationTypeMemberDeclaration.<init>(AnnotationTypeMemberDeclaration.java:35)
	at com.google.devtools.j2objc.ast.TreeConverter.convertInner(TreeConverter.java:67)
	at com.google.devtools.j2objc.ast.TreeConverter.convert(TreeConverter.java:56)
	at com.google.devtools.j2objc.ast.AbstractTypeDeclaration.<init>(AbstractTypeDeclaration.java:40)
	at com.google.devtools.j2objc.ast.AnnotationTypeDeclaration.<init>(AnnotationTypeDeclaration.java:23)
	at com.google.devtools.j2objc.ast.TreeConverter.convertInner(TreeConverter.java:64)
	at com.google.devtools.j2objc.ast.TreeConverter.convert(TreeConverter.java:56)
	at com.google.devtools.j2objc.ast.CompilationUnit.<init>(CompilationUnit.java:72)
	at com.google.devtools.j2objc.ast.TreeConverter.convertCompilationUnit(TreeConverter.java:28)
	at com.google.devtools.j2objc.TranslationProcessor.processUnit(TranslationProcessor.java:223)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:214)
	at com.google.devtools.j2objc.TranslationProcessor.processSource(TranslationProcessor.java:212)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:192)
	at com.google.devtools.j2objc.FileProcessor.processJavaFile(FileProcessor.java:113)
	at com.google.devtools.j2objc.FileProcessor.processSourceFile(FileProcessor.java:99)
	at com.google.devtools.j2objc.FileProcessor.processFile(FileProcessor.java:71)
	at com.google.devtools.j2objc.FileProcessor.processFiles(FileProcessor.java:62)
	at com.google.devtools.j2objc.TranslationProcessor.processFiles(TranslationProcessor.java:129)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:197)
```

Here's how one would use the annotation:
```
public class SomeClass {
  @ComplexAnnotate(anAttribute=@SimpleAnnotate)
  public boolean someMethod() {
    return true;
  }
}
```

**Comment by tomball** [comment]
com.j2objc.devtools.j2objc.ast.Annotation needed to extend Expression, not TreeNode.

**Comment by harrycheung** [comment]
I've spent a little time looking at this since I wanted it working sooner than later. In addition to changing Annotation's inheritance, the trickier part is how to translate defaultValue. The Expression node gets sent to StatementGenerator.generate. The expression "@SimpleAnnotate" should translate to "[[SimpleAnnotate alloc] init];", which isn't a normal expression except in this annotation case. Maybe a mutation should be used?

**Comment by harrycheung** [comment]
Something like ArrayRewriter would work, but then I'm worried about how the declaration gets handled since that should be handled differently. The Annotation node should be changed to a MethodInvocation node only for generating the default value it seems.

**Comment by harrycheung** [comment]
I have something working. If you don't mind, I'll send a PR after I clean it up and fix up the unit test.

**Comment by harrycheung** [comment]
@tomball, I've finished fixing annotations, and I'm ready to send a PR. However, I need to use the code from my other PR pertaining to 'IOSClass.classFromClass', which isn't in the public master. I'm afraid of mixing the two PRs so I'm looking for advice on how to submit it.

**Comment by tomball** [comment]
Fixed in current source.
