### ISSUE TITLE
AssertionError when transpiling Java files with annotation-based valued annotations

### ISSUE THREAD

**Issue by MiguelGL** [google/j2objc#504]
Hello, I am finding an error when transpiling Java sources annotated with some annotations having values which in turn are (arrays of) annotations themselves. Take for example JPA [@Table(indexes={...})] (http://docs.oracle.com/javaee/7/api/javax/persistence/Table.html#indexes()) or [JAXB @XmlSchema(xmlns={...})] (http://docs.oracle.com/javaee/7/api/javax/xml/bind/annotation/XmlSchema.html#xmlns()). 

I am using: *version 0.9.6.1* downloaded from the releases area.

I observed there have been fixes to annotations stuff in the project but assumed they do not apply to the problem here since the release date is after the changes #470, #471. My appologies if this has already been fixed but not yet made public. Described error traces are also different to what I am encountering.

I published a demo project to reproduce the issue: https://github.com/MiguelGL/j2objc-tests

Just clone it and run:

    $ git clone https://github.com/MiguelGL/j2objc-tests.git
    $ cd j2objc-tests
    $ mvn clean install
    $ ./basic-compile.sh

The compiling script is a straightforward call to transpile the problematic file, reproduced next:

```java
package com.mgl.j2objctests;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
// --> This works: @Table(name = "jpa_entity_test")
// --x The following does not:
@Table(indexes = {
      @Index(columnList = "email")})
// --x The following does not either:
//@Table(uniqueConstraints = {
//    @UniqueConstraint(columnNames = {"email"}),
//    @UniqueConstraint(columnNames = {"uuid"})})
public class JpaEntityTest implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id @GeneratedValue
    private Long id;

    private String email;

    private String uuid;

    // getters, setters, etc.
}
```

This is the error stacktrace:

```
translating src/main/java/com/mgl/j2objctests/JpaEntityTest.java
Exception in thread "main" java.lang.AssertionError: unknown annotation value type
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationValue(ObjectiveCImplementationGenerator.java:680)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationValue(ObjectiveCImplementationGenerator.java:676)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationParameters(ObjectiveCImplementationGenerator.java:651)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotations(ObjectiveCImplementationGenerator.java:629)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationCreate(ObjectiveCImplementationGenerator.java:611)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printTypeAnnotationsMethod(ObjectiveCImplementationGenerator.java:542)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.generate(ObjectiveCImplementationGenerator.java:184)
	at com.google.devtools.j2objc.gen.ObjectiveCSourceFileGenerator.generate(ObjectiveCSourceFileGenerator.java:83)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.generate(ObjectiveCImplementationGenerator.java:105)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.generate(ObjectiveCImplementationGenerator.java:79)
	at com.google.devtools.j2objc.TranslationProcessor.generateObjectiveCSource(TranslationProcessor.java:401)
	at com.google.devtools.j2objc.TranslationProcessor.processUnit(TranslationProcessor.java:235)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:214)
	at com.google.devtools.j2objc.TranslationProcessor.processSource(TranslationProcessor.java:212)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:192)
	at com.google.devtools.j2objc.FileProcessor.processJavaFile(FileProcessor.java:113)
	at com.google.devtools.j2objc.FileProcessor.processSourceFile(FileProcessor.java:99)
	at com.google.devtools.j2objc.FileProcessor.processFile(FileProcessor.java:71)
	at com.google.devtools.j2objc.FileProcessor.processFiles(FileProcessor.java:62)
	at com.google.devtools.j2objc.TranslationProcessor.processFiles(TranslationProcessor.java:129)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:197)
```

Thanks for everything, this project is so great!

**Comment by tomball** [comment]
Congratulations! You are the first developer to try transpiling an annotation that has other annotations as properties. :-)

I just added that support, but it will take a few days for the commit to get code-reviewed, then pushed to the public repository.

**Comment by MiguelGL** [comment]
That's great. I'm glad I could contribute. I am sincerely impressed by the work you and your team are doing here, #respect :) Thanks!

**Comment by tomball** [comment]
Fixed in current source.
