### ISSUE TITLE
AssertionError: Can't assign j2objc.ast.FunctionInvocation to j2objc.ast.SimpleName

### ISSUE THREAD

**Issue by samirahmed** [google/j2objc#515]
Hey there, 

I don't really know how to investigate this exception i get (using the latest release `0.9.6.1`)

Below is the stack trace

```
translating ./ews-java-api/src/main/java/microsoft/exchange/webservices/data/core/ExchangeService.java
Exception in thread "main" java.lang.AssertionError: Cannot assign node of type com.google.devtools.j2objc.ast.FunctionInvocation to child of type com.google.devtools.j2objc.ast.SimpleName
	at com.google.devtools.j2objc.ast.ChildLink.setDynamic(ChildLink.java:64)
	at com.google.devtools.j2objc.ast.TreeNode.replaceWith(TreeNode.java:78)
	at com.google.devtools.j2objc.translate.StaticVarRewriter.visitName(StaticVarRewriter.java:93)
	at com.google.devtools.j2objc.translate.StaticVarRewriter.visit(StaticVarRewriter.java:75)
	at com.google.devtools.j2objc.ast.SimpleName.acceptInner(SimpleName.java:67)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.FieldAccess.acceptInner(FieldAccess.java:79)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.FunctionInvocation.acceptInner(FunctionInvocation.java:81)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.MethodInvocation.acceptInner(MethodInvocation.java:99)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.FunctionInvocation.acceptInner(FunctionInvocation.java:81)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ReturnStatement.acceptInner(ReturnStatement.java:54)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.SwitchStatement.acceptInner(SwitchStatement.java:62)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:62)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.FunctionDeclaration.acceptInner(FunctionDeclaration.java:77)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:87)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:184)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:100)
	at com.google.devtools.j2objc.ast.TreeVisitor.run(TreeVisitor.java:29)
	at com.google.devtools.j2objc.TranslationProcessor.applyMutations(TranslationProcessor.java:354)
	at com.google.devtools.j2objc.TranslationProcessor.processUnit(TranslationProcessor.java:225)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:214)
	at com.google.devtools.j2objc.TranslationProcessor.processSource(TranslationProcessor.java:212)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:192)
	at com.google.devtools.j2objc.FileProcessor.processJavaFile(FileProcessor.java:131)
	at com.google.devtools.j2objc.FileProcessor.processSourceFile(FileProcessor.java:99)
	at com.google.devtools.j2objc.FileProcessor.processFile(FileProcessor.java:71)
	at com.google.devtools.j2objc.FileProcessor.processFiles(FileProcessor.java:62)
	at com.google.devtools.j2objc.TranslationProcessor.processFiles(TranslationProcessor.java:129)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:197)
```

The file in question is viewable [here](https://github.com/OfficeDev/ews-java-api/blob/master/src/main/java/microsoft/exchange/webservices/data/core/ExchangeService.java)

From the stack trace the term 'staticVarRewriter' ... there is only 1 static variable in that file + only 1 switch statement.  

Please let me know what else I can do to debug this error.

**Comment by kstanger** [comment]
This expression is almost certainly the culprit: "autodiscoverService.isExternal().TRUE"

Thanks for the report!

**Comment by kstanger** [comment]
Fixed in public source.
