### ISSUE TITLE
NullPointerException when translating libgdx

### ISSUE THREAD

**Issue by vinaysshenoy** [google/j2objc#551]
I'm trying to translate libgdx into ObjC. Most of the source files go through fine, except for one. The offending file is https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/particles/renderers/ModelInstanceRenderer.java

When I try to translate this, it fails with the following exception.

`Exception in thread "main" java.lang.NullPointerException
	at com.google.devtools.j2objc.ast.TreeUtil.getVariableBinding(TreeUtil.java:206)
	at com.google.devtools.j2objc.translate.CastResolver.getDeclaredType(CastResolver.java:163)
	at com.google.devtools.j2objc.translate.CastResolver.needsCast(CastResolver.java:140)
	at com.google.devtools.j2objc.translate.CastResolver.endVisit(CastResolver.java:296)
	at com.google.devtools.j2objc.ast.QualifiedName.acceptInner(QualifiedName.java:73)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.Assignment.acceptInner(Assignment.java:134)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.ForStatement.acceptInner(ForStatement.java:83)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:62)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.MethodDeclaration.acceptInner(MethodDeclaration.java:113)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:87)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:206)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.TreeVisitor.run(TreeVisitor.java:29)
	at com.google.devtools.j2objc.TranslationProcessor.applyMutations(TranslationProcessor.java:335)
	at com.google.devtools.j2objc.TranslationProcessor.processCompiledGenerationUnit(TranslationProcessor.java:176)
	at com.google.devtools.j2objc.FileProcessor.processCompilationUnit(FileProcessor.java:183)
	at com.google.devtools.j2objc.TranslationProcessor.processCompilationUnit(TranslationProcessor.java:159)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:150)
	at com.google.devtools.j2objc.FileProcessor.processBatch(FileProcessor.java:104)
	at com.google.devtools.j2objc.FileProcessor.processGenerationUnit(FileProcessor.java:77)
	at com.google.devtools.j2objc.TranslationProcessor.processBatch(TranslationProcessor.java:132)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:185)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:228)`

Any idea what the issue could be and how I could go about getting this file translated as well?

**Comment by vinaysshenoy** [comment]
Any idea? This is critical for us, so even an inkling of how to go about fixing this would be super helpful.

**Comment by kstanger** [comment]
I'm gonna take a look at this now.

**Comment by vinaysshenoy** [comment]
Thank you very much! We only want to translate the "gdx" package, which is available at https://github.com/libgdx/libgdx/tree/master/gdx/src/com/badlogic/gdx, if it helps.

**Comment by kstanger** [comment]
I have a fix for this specific issue that I'll try to get pushed out soon.

**Comment by vinaysshenoy** [comment]
Thanks a ton!

**Comment by kstanger** [comment]
Fixed in latest source:
https://github.com/google/j2objc/commit/51027f450381dfd75a4944bfb9219cea712f37f7

**Comment by vinaysshenoy** [comment]
Excellent! Thanks for the quick fix!

On Mon, Jun 22, 2015 at 7:08 PM, Keith Stanger <notifications@github.com>
wrote:

> Fixed in latest source:
>
> https://github.com/google/j2objc/commit/51027f450381dfd75a4944bfb9219cea712f37f7
>
> On Fri, 19 Jun 2015 at 14:12 Vinay S Shenoy <notifications@github.com>
> wrote:
>
> > Thanks a ton!
> > On Jun 19, 2015 11:41 PM, "Keith Stanger" <notifications@github.com>
> > wrote:
> >
> > > I have a fix for this specific issue that I'll try to get pushed out
> > soon.
> > >
> > > On Fri, 19 Jun 2015 at 13:24 Vinay S Shenoy <notifications@github.com>
> > > wrote:
> > >
> > > > Thank you very much! We only want to translate the "gdx" package,
> which
> > > is
> > > > available at
> > > >
> https://github.com/libgdx/libgdx/tree/master/gdx/src/com/badlogic/gdx,
> > > if
> > > > it helps.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/google/j2objc/issues/551#issuecomment-113581155
> >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/google/j2objc/issues/551#issuecomment-113594474>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/j2objc/issues/551#issuecomment-113595088>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/j2objc/issues/551#issuecomment-114106221>.
>



-- 
Vinay S Shenoy
Mobile Architect at Stealth Startup
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy
