### ISSUE TITLE
java.lang.AssertionError when translating Java files with annotations

### ISSUE THREAD

**Issue by Qata** [google/j2objc#658]
I'm using 0.9.8.2.1 and I'm trying to use J2ObjC to compile a Java file that itself was compiled from Frege by fregec.
After a little messing around I've gotten a frege.jar with all the necessary files as .java instead of .class. (This can be downloaded [here](https://www.dropbox.com/s/fjdvdszcgn3ddac/frege.jar?dl=0)).
Trying to compile against frege.jar (or even solely frege.jar) results in this:
```
Exception in thread "main" java.lang.AssertionError: unknown annotation value type
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationValue(ObjectiveCImplementationGenerator.java:680)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationValue(ObjectiveCImplementationGenerator.java:676)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationParameters(ObjectiveCImplementationGenerator.java:651)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotations(ObjectiveCImplementationGenerator.java:629)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printAnnotationCreate(ObjectiveCImplementationGenerator.java:611)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.printTypeAnnotationsMethod(ObjectiveCImplementationGenerator.java:542)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.generate(ObjectiveCImplementationGenerator.java:184)
	at com.google.devtools.j2objc.gen.ObjectiveCSourceFileGenerator.generate(ObjectiveCSourceFileGenerator.java:83)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.generate(ObjectiveCImplementationGenerator.java:105)
	at com.google.devtools.j2objc.gen.ObjectiveCImplementationGenerator.generate(ObjectiveCImplementationGenerator.java:79)
	at com.google.devtools.j2objc.TranslationProcessor.generateObjectiveCSource(TranslationProcessor.java:401)
	at com.google.devtools.j2objc.TranslationProcessor.processUnit(TranslationProcessor.java:235)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:214)
	at com.google.devtools.j2objc.TranslationProcessor.processSource(TranslationProcessor.java:212)
	at com.google.devtools.j2objc.FileProcessor.processJarFile(FileProcessor.java:179)
	at com.google.devtools.j2objc.FileProcessor.processSourceFile(FileProcessor.java:101)
	at com.google.devtools.j2objc.FileProcessor.processFile(FileProcessor.java:71)
	at com.google.devtools.j2objc.FileProcessor.processFiles(FileProcessor.java:62)
	at com.google.devtools.j2objc.TranslationProcessor.processFiles(TranslationProcessor.java:129)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:197)
```

**Comment by kstanger** [comment]
Are you able to track down the file, or line of code where this is failing? That will save Tom or I some time trying to solve this.

**Comment by Qata** [comment]
I have zero experience with Java, sorry. I wouldn't even know what to look for.

**Comment by kstanger** [comment]
Run j2objc with the -v flag (verbose logging). That should at least identify the file that's failing.

**Comment by Qata** [comment]
I'll do that first thing when I get to the office. 👌

**Comment by tomball** [comment]
I can't duplicate this translator issue with the latest source, so
hopefully it's fixed.

I noticed, though, that Frege has lots of dependencies on classes that
aren't supported by Android (like AWT, Swing, java.nio.file,
Locale.Category and Pattern.UNICODE_CHARACTER_CLASS), or even make sense on
any handheld device (like Process, ProcessBuilder, javax.tools, etc.).
While you're welcome to extend j2objc for OS X apps, we don't have the
resources to support you, as this project is focused on iOS and based on
Android JRE source.

**Comment by Qata** [comment]
Ah that's such a shame, I was hoping to use it with iOS. Thanks for the help!
