### ISSUE TITLE
NullPointerException when translating com.google.gwt.core.client.GWT class

### ISSUE THREAD

**Issue by dholzenburg** [google/j2objc#689]
Hi,

I am trying to translate newest requestfactory-client-2.8.0-beta1, but it fails with a NullPointerException.

```
translating /Users/blabla/NetBeansProjects/j2objc-test/target/classes/requestfactory-client/com/google/gwt/core/client/GWT.java
Exception in thread "main" java.lang.NullPointerException
	at com.google.devtools.j2objc.translate.GwtConverter.visit(GwtConverter.java:89)
	at com.google.devtools.j2objc.ast.IfStatement.acceptInner(IfStatement.java:73)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:62)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.MethodDeclaration.acceptInner(MethodDeclaration.java:113)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:87)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:203)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:104)
	at com.google.devtools.j2objc.ast.TreeVisitor.run(TreeVisitor.java:39)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:131)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:91)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:171)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInput(FileProcessor.java:117)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:69)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:71)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:138)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:173)
```

Is this untranslatable code at all or just a bug? 

My goal is to use the EventBus provided by this library. If one could use the whole RequestFactory thing with iOS it would be really great, but the primary use would be the EventBus.

The GWT Compiler (using it since years) and J2ObjC (using it since yesterday :-) ) are amazing pieces of software. Thanks for providing such cool tools.

Many thanks in advance for having a look on this one.

Regards, Dirk

**Comment by tomball** [comment]
Fixed in [latest source](https://github.com/google/j2objc/commit/dd5b1c13d81665a385a1b75f22e05c43e3435c7e).
