### ISSUE TITLE
Problem when translating generated code that have default method that `super` keyword

### ISSUE THREAD

**Issue by mahmoud-khalifa** [google/j2objc#743]
I have problems when translating generated sources that have default methods that use `super` 

Here is the original code 

    @Value.Derived
    default String regexPattern() {
        return value().replaceAll("\\+", "[^/]+").replaceAll("#", ".+");
    }

and here is the generated code method that fails
     
    private ImmutableTopicPattern(String value) {
        this.value = Preconditions.checkNotNull(value, "value");
        this.regexPattern = Preconditions.checkNotNull(TopicPattern.super.regexPattern(), "regexPattern");
    }

I got exception while translating the following line 
`this.regexPattern = Preconditions.checkNotNull(TopicPattern.super.regexPattern(), "regexPattern");`

Here is the Exception stack trace

    com.google.devtools.j2objc.ast.TreeVisitorAssertionError: testProject/target/generated-sources/annotations/com/company/services/api/ImmutableTopicPattern.java:23: null
	at com.google.devtools.j2objc.translate.OuterReferenceFixer.fixPath(OuterReferenceFixer.java:187)
	at com.google.devtools.j2objc.translate.OuterReferenceFixer.endVisit(OuterReferenceFixer.java:139)
	at com.google.devtools.j2objc.ast.SuperMethodInvocation.acceptInner(SuperMethodInvocation.java:95)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.MethodInvocation.acceptInner(MethodInvocation.java:114)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.Assignment.acceptInner(Assignment.java:140)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ExpressionStatement.acceptInner(ExpressionStatement.java:54)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:62)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.MethodDeclaration.acceptInner(MethodDeclaration.java:113)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:87)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:203)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.TreeVisitor.run(TreeVisitor.java:39)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:186)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:96)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:172)
	at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:42)
	at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:144)
	at com.google.devtools.j2objc.util.JdtParser$1.acceptAST(JdtParser.java:165)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1029)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
	at com.google.devtools.j2objc.util.JdtParser.parseFiles(JdtParser.java:174)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:152)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:71)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:76)

**Comment by kstanger** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/48ba0563ad86a096a7a2070981f74a5373ad419d).

**Comment by mahmoud-khalifa** [comment]
Thanks :)
