### ISSUE TITLE
internal error java.lang.NullPointerException 

### ISSUE THREAD

**Issue by accidbright** [google/j2objc#769]
In 1.0.2 version some files can't be generated with the next error

```
error: internal error translating "/Users/Ihar.Patsousky/Documents/Projects/Digitalchemy/Redist/redist/Core/Foundation/iOS/../../../Core/Foundation/Java/Neutral/src/com/digitalchemy/foundation/advertising/configuration/AdMediatorConfiguration.java"
java.lang.NullPointerException
	at com.google.devtools.j2objc.translate.NilCheckResolver$Scope.mergeDownAndReset(NilCheckResolver.java:181)
	at com.google.devtools.j2objc.translate.NilCheckResolver$Scope.access$1100(NilCheckResolver.java:100)
	at com.google.devtools.j2objc.translate.NilCheckResolver.handleConditional(NilCheckResolver.java:526)
	at com.google.devtools.j2objc.translate.NilCheckResolver.visit(NilCheckResolver.java:511)
	at com.google.devtools.j2objc.ast.ConditionalExpression.acceptInner(ConditionalExpression.java:81)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.VariableDeclarationFragment.acceptInner(VariableDeclarationFragment.java:46)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.FieldDeclaration.acceptInner(FieldDeclaration.java:75)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.translate.NilCheckResolver.visitType(NilCheckResolver.java:478)
	at com.google.devtools.j2objc.translate.NilCheckResolver.visit(NilCheckResolver.java:500)
	at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:81)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:203)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.TreeVisitor.run(TreeVisitor.java:39)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:198)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:96)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:172)
	at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:42)
	at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:144)
	at com.google.devtools.j2objc.util.JdtParser$1.acceptAST(JdtParser.java:165)
	at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1029)
	at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
	at j2objc.org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
	at com.google.devtools.j2objc.util.JdtParser.parseFiles(JdtParser.java:174)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:152)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInput(FileProcessor.java:96)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:69)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:76)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:139)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:174)
```

Previous versions (including 1.0.1) of j2objc works good with these files. Do I miss something when updating the tool or is this a bug?

**Comment by tomball** [comment]
It's a bug, as the compiler should always run regardless of input. Can you provide a test that demonstrates this problem? If your source is private, it can probably be scrubbed -- it looks like a variable declaration is being initialized with a conditional expression, so that declaration is probably all that's needed (my attempts at writing a test based on the stack trace all build).

**Comment by accidbright** [comment]
Thanks for the explanation, I couldn't determine wha's wrong before it. Now I see the wrong line, but I attach a bit more of code

**AdMediatorConfiguration.java** (class that fails)
```
public class AdMediatorConfiguration
{
	private static final Log log = LogFactory.GetLogger("AdMediatorConfiguration");
	private static final int DEFAULT_AD_REFRESH_INTERVAL_SECONDS = Conditional.Debug ? 10 : 30;

	public AdMediatorConfiguration()
	{
	}
}
```

**AdUnitMediator.java** (another class that fails, stack trace looks the same, but if necessary, I can attach it too)
```
public class AdUnitMediator implements IAdUnitMediator
{
	private static final Log log = LogFactory.GetLogger("AdUnitMediator");
	public static final int MINIMUM_AD_DISPLAY_SECONDS = Conditional.Debug ? 5 : 20;

	public AdUnitMediator()
	{
	}
}
```

**Conditional.java** (for any case to understand what is Debug variable)
```
public final class Conditional
{
	public static final boolean Debug = false;
}
```

**Comment by tomball** [comment]
The good news is that this test fails to compile with 1.0.2 as you reported, and compiles successfully with the current source. The bad news is that you have to build from source if you want the fix now. :-)

First run `git clone https://github.com/google/j2objc.git` to create a copy of the latest source, then follow [the build instructions](http://j2objc.org/docs/Building-J2ObjC.html) (you only need to run `make dist` unless your project uses J2ObjC's frameworks).
