### ISSUE TITLE
Exception while translating Enum

### ISSUE THREAD

**Issue by mdiiorio** [google/j2objc#782]
Using j2objc 1.1, the code

```
import java.util.concurrent.atomic.*;
import java.util.*;

class Item extends AtomicBoolean {
}

class OtherItem extends HashSet<Item> {
}

public enum Enum {

  ITEM(OtherItem.class, Item.class) {
  };

  private final Class<? extends Set> otherItemClass;
  private final Class<? extends AtomicBoolean> protoClass;

  <T extends AtomicBoolean> Enum(Class<? extends Set<T>> otherItemClass, Class<T> protoClass) {
    this.otherItemClass = otherItemClass;
    this.protoClass = protoClass;
  }
}
```

results in the exception

```
com.google.devtools.j2objc.ast.TreeVisitorAssertionError: Enum.java:12: could not find constructor
        at com.google.devtools.j2objc.translate.AnonymousClassConverter.findSuperConstructorBinding(AnonymousClassConverter.java:179)
        at com.google.devtools.j2objc.translate.AnonymousClassConverter.addDefaultConstructor(AnonymousClassConverter.java:137)
        at com.google.devtools.j2objc.translate.AnonymousClassConverter.endVisit(AnonymousClassConverter.java:93)
        at com.google.devtools.j2objc.ast.AnonymousClassDeclaration.acceptInner(AnonymousClassDeclaration.java:73)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:106)
        at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
        at com.google.devtools.j2objc.ast.EnumConstantDeclaration.acceptInner(EnumConstantDeclaration.java:103)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:106)
        at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
        at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
        at com.google.devtools.j2objc.ast.EnumDeclaration.acceptInner(EnumDeclaration.java:65)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:106)
        at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
        at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
        at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:199)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:106)
        at com.google.devtools.j2objc.ast.TreeVisitor.run(TreeVisitor.java:39)
        at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:181)
        at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:100)
        at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:173)
        at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:43)
        at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:145)
        at com.google.devtools.j2objc.util.JdtParser$1.acceptAST(JdtParser.java:165)
        at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1029)
        at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
        at j2objc.org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
        at com.google.devtools.j2objc.util.JdtParser.parseFiles(JdtParser.java:174)
        at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:153)
        at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:72)
        at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:80)
        at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:139)
        at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:174)
```

**Comment by tomball** [comment]
Problem appears to be j2objc has never run into an enum constructor with a type parameter before. Since enums are supposed to be constants and their constructors non-publicwith a type parameter doesn't make sense to me, but apparently it's legal Java (besides, javac erases the type parameter).

Until this is fixed, a workaround is to remove the type parameter everywhere.

**Comment by mdiiorio** [comment]
The example is nonsensical, but it's fashioned after a piece of code in a project I'm attempting to translate where it makes a a bit more sense :) I was able to remove the type parameter and get it translated.

**Comment by kstanger** [comment]
Fixing this correctly is quite difficult. The JDT doesn't appear to provide any indication of which superclass constructor should be called from the implicitly declared anonymous class constructor. To determine the correct super constructor we would have to implement [JLS 15.12.2](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.2), which is quite a daunting task. Hopefully once we switch to the javac parser it might provide a better hint at which super constructor to call.

**Comment by kstanger** [comment]
I just verified that this is fixed with our Javac parser. It shouldn't be too much longer before we are able to make that switch.

**Comment by kstanger** [comment]
The Javac parser is now the default in current source.
