### ISSUE TITLE
cannot translate org.apache.ant

### ISSUE THREAD

**Issue by tux-mind** [google/j2objc#809]
cannot translate the [ant core project](https://mvnrepository.com/artifact/org.apache.ant/ant/1.9.7).

```
error: internal error translating "/path/to/root/project/external/ant/build/mainTranslationExtraction/org/apache/tools/bzip2/BlockSort.java"
  java.lang.NullPointerException
        at com.google.devtools.j2objc.translate.NilCheckResolver$Scope.mergeDownAndReset(NilCheckResolver.java:181)
        at com.google.devtools.j2objc.translate.NilCheckResolver$Scope.access$1100(NilCheckResolver.java:100)
        at com.google.devtools.j2objc.translate.NilCheckResolver.handleConditional(NilCheckResolver.java:526)
        at com.google.devtools.j2objc.translate.NilCheckResolver.visit(NilCheckResolver.java:511)
        at com.google.devtools.j2objc.ast.ConditionalExpression.acceptInner(ConditionalExpression.java:81)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
        at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
        at com.google.devtools.j2objc.ast.VariableDeclarationFragment.acceptInner(VariableDeclarationFragment.java:46)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
        at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
        at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
        at com.google.devtools.j2objc.ast.FieldDeclaration.acceptInner(FieldDeclaration.java:75)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
        at com.google.devtools.j2objc.translate.NilCheckResolver.visitType(NilCheckResolver.java:478)
        at com.google.devtools.j2objc.translate.NilCheckResolver.visit(NilCheckResolver.java:500)
        at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:81)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
        at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
        at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
        at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:203)
        at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
        at com.google.devtools.j2objc.ast.TreeVisitor.run(TreeVisitor.java:39)
        at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:198)
        at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:96)
        at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:172)
        at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:42)
        at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:144)
        at com.google.devtools.j2objc.util.JdtParser$1.acceptAST(JdtParser.java:165)
        at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1029)
        at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
        at j2objc.org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
        at com.google.devtools.j2objc.util.JdtParser.parseFiles(JdtParser.java:174)
        at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:152)
        at com.google.devtools.j2objc.pipeline.FileProcessor.processInput(FileProcessor.java:96)
        at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:69)
        at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:76)
        at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:139)
        at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:174)
```

Thanks for the great work, it's simply awesome :sunglasses:

**Comment by kstanger** [comment]
I believe this to be fixed by [this commit](https://github.com/google/j2objc/commit/c29e85775cb32e77f91479843f3c6c7e4e36f9c9), which is in both the 1.1 and 1.2 releases. I'm going to add a regression test.
