### ISSUE TITLE
New Bug converting Java to ObjC

### ISSUE THREAD

**Issue by simmese** [google/j2objc#816]
Please Help! I have this trace:

java.lang.NullPointerException
at com.google.devtools.j2objc.translate.NilCheckResolver.handleConditional(NilCheckResolver.java:556)
at com.google.devtools.j2objc.translate.NilCheckResolver.visit(NilCheckResolver.java:539)
at com.google.devtools.j2objc.ast.IfStatement.acceptInner(IfStatement.java:69)
at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:55)
at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
at com.google.devtools.j2objc.translate.NilCheckResolver.visit(NilCheckResolver.java:504)
at com.google.devtools.j2objc.ast.MethodDeclaration.acceptInner(MethodDeclaration.java:138)
at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
at com.google.devtools.j2objc.translate.NilCheckResolver.visitType(NilCheckResolver.java:512)
at com.google.devtools.j2objc.translate.NilCheckResolver.visit(NilCheckResolver.java:534)
at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:106)
at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:209)
at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
at com.google.devtools.j2objc.ast.UnitTreeVisitor.run(UnitTreeVisitor.java:39)
at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:210)
at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:103)
at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:151)
at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:38)
at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:129)
at com.google.devtools.j2objc.jdt.JdtParser$1.acceptAST(JdtParser.java:168)
at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1029)
at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
at j2objc.org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
at com.google.devtools.j2objc.jdt.JdtParser.parseFiles(JdtParser.java:180)
at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:134)
at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:66)
at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:81)
at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:146)
at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:183)

**Comment by tomball** [comment]
Can you attach either the source code or an example? Also, what version are you using? [The latest NilCheckResolver.java:556](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/translate/NilCheckResolver.java#L556) doesn't point to a code statement. [Here are the instructions to build the latest.](http://j2objc.org/docs/Building-J2ObjC.html)

**Comment by simmese** [comment]
I'm building the latest already.

Many thanks for your awesome work!!

Simone Giacometti (from Turin, Italy)


2016-11-17 16:32 GMT+01:00 Tom Ball <notifications@github.com>:

**Comment by tomball** [comment]
That stack trace isn't from the latest source, as NilCheckResolver.java:556
doesn't refer to a statement. Please do a "git pull" and rebuild, then post
an updated stack trace. If that isn't possible, please attach some source
that demonstrates this problem.

While you're doing that, I'll investigate how to improve the exception
handling so the node that triggered the problem gets logged.

**Comment by simmese** [comment]
I just finished the build using "make frameworks" (2 hours long!). Where is now the j2objc executable? I cannot find it after the build...

**Comment by kstanger** [comment]
From the root directory (where you ran "make frameworks") it's at
dist/j2objc.

**Comment by simmese** [comment]
Many thanks!!

**Comment by tomball** [comment]
Cannot reproduce, assume fixed.
