### ISSUE TITLE
StackOverflowError When Using cycle_finder

### ISSUE THREAD

**Issue by congt** [google/j2objc#820]
The following code will cause StackOverflowError in cycle_finder:

Code:
```
public class Foo<E> {
  public Foo<List<E>> listFoo;
}
```

Stacktrace:
```
Exception in thread "main" java.lang.StackOverflowError
	at j2objc.org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.computeUniqueKey(TypeVariableBinding.java:283)
	at j2objc.org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.computeUniqueKey(ParameterizedTypeBinding.java:336)
	at j2objc.org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.computeUniqueKey(ParameterizedTypeBinding.java:336)
	...
```

**Comment by tomball** [comment]
This is an Eclipse JDT bug, and is an example of why we've been working so hard lately converting the translator to use javac as its front-end instead of JDT (as you probably noticed, javac has no problem compiling this class). Keith is currently working on converting cycle_finder, and we'll add this sample as a unit test for it.

**Comment by congt** [comment]
That will be great! Thanks.

**Comment by kstanger** [comment]
Fixed in current source.
