### ISSUE TITLE
TreeVisitorError: Cannot assign node of type com.google.devtools.j2objc.ast.QualifiedName to child of type com.google.devtools.j2objc.ast.SimpleName

### ISSUE THREAD

**Issue by guilhermesgb** [google/j2objc#836]
I'm getting the following error when I try to translate [this file](https://gist.github.com/guilhermesgb/7197592b2a7a1037174e89c939a023f4).

```
error: internal error translating "./src/android/gov/nist/javax/sip/stack/NioTlsWebSocketMessageChannel.java"
com.google.devtools.j2objc.ast.TreeVisitorError: ./src/android/gov/nist/javax/sip/stack/NioTlsWebSocketMessageChannel.java:137: Cannot assign node of type com.google.devtools.j2objc.ast.QualifiedName to child of type com.google.devtools.j2objc.ast.SimpleName
	at com.google.devtools.j2objc.ast.ChildLink.setDynamic(ChildLink.java:65)
	at com.google.devtools.j2objc.ast.TreeNode.replaceWith(TreeNode.java:68)
	at com.google.devtools.j2objc.translate.OuterReferenceResolver.visit(OuterReferenceResolver.java:400)
	at com.google.devtools.j2objc.ast.SimpleName.acceptInner(SimpleName.java:83)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.SuperFieldAccess.acceptInner(SuperFieldAccess.java:80)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.SuperMethodInvocation.acceptInner(SuperMethodInvocation.java:131)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ExpressionStatement.acceptInner(ExpressionStatement.java:52)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:55)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.MethodDeclaration.acceptInner(MethodDeclaration.java:142)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:109)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ClassInstanceCreation.acceptInner(ClassInstanceCreation.java:179)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.MethodInvocation.acceptInner(MethodInvocation.java:133)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ExpressionStatement.acceptInner(ExpressionStatement.java:52)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:55)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.TryStatement.acceptInner(TryStatement.java:85)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:55)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.IfStatement.acceptInner(IfStatement.java:71)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:55)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.MethodDeclaration.acceptInner(MethodDeclaration.java:142)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:109)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:91)
	at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:174)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.UnitTreeVisitor.run(UnitTreeVisitor.java:50)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:141)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:101)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:158)
	at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:39)
	at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:136)
	at com.google.devtools.j2objc.jdt.JdtParser$1.acceptAST(JdtParser.java:179)
	at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1029)
	at j2objc.org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
	at j2objc.org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
	at com.google.devtools.j2objc.jdt.JdtParser.parseFiles(JdtParser.java:191)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:141)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInput(FileProcessor.java:96)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:68)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:77)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:125)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:166)
```

I have no idea how to go about fixing my file so that it avoids this problem. Any help is appreciated!

Thanks in advance :)

**Comment by tomball** [comment]
Would you please add a link to the source for this project? With the full source, we'll be able to debug this problem, and should be able to fix the translator quickly.

If the full source isn't available, please add a gist to the NioWebSocketMessageChannel.java file, which (I assume) is the "super" referred to at line 137.

**Comment by guilhermesgb** [comment]
Hey, thank you for the quick reply. We can't disclose the full source, but luckily the problem actually happens in one of our dependencies (which is repackaged and bundled alongside our source code) so I'll prepare a separate project with just that portion, retry translating it just to make sure the exact same problem persists, and then I'll link you to it. It should be available in a couple hours, first thing in the morning I'll work on that.

Many thanks again! :)

**Comment by tomball** [comment]
Thanks. We don't need the whole project, just what the declarations are for
the .super method and field references. If you can duplicate the problem
with a simple pair of test classes, that's all we need.

**Comment by guilhermesgb** [comment]
Here you go, not the whole project but a bit more of context than just two classes (it was more convenient for me): https://github.com/guilhermesgb/JavaxSipStack

I've tested and the problem is reproducible using this project.

**Comment by kstanger** [comment]
Thanks for the detailed report. It seems the issue applies to all qualified super field access expressions (eg. "Foo.super.bar") so it's hard to believe this has gone unnoticed until now! I've got a fix on the way.

**Comment by kstanger** [comment]
Fixed in current source.

**Comment by guilhermesgb** [comment]
Thanks for the fix!
