### ISSUE TITLE
NullPointerException when translate conditional expression.

### ISSUE THREAD

**Issue by kingxt** [google/j2objc#875]
When i translate expression bellow, the translator throw exception.

``` java
public final void storeRecommendedBotList(final ImmutableList<Long> userIdList, final long expiryTime) {
        store(RECOMMENDED_BOT_LIST, userIdList.isEmpty() ? "" : Strings.joinLong(userIdList, ','));
}
```

``` java
t com.google.devtools.j2objc.util.UnicodeUtils.escapeStringLiteral(UnicodeUtils.java:53)
	at com.google.devtools.j2objc.ast.DebugASTPrinter.visit(DebugASTPrinter.java:885)
	at com.google.devtools.j2objc.ast.StringLiteral.acceptInner(StringLiteral.java:75)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.DebugASTPrinter.visit(DebugASTPrinter.java:273)
	at com.google.devtools.j2objc.ast.ConditionalExpression.acceptInner(ConditionalExpression.java:84)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.ast.DebugASTPrinter.toString(DebugASTPrinter.java:45)
	at com.google.devtools.j2objc.ast.TreeNode.toString(TreeNode.java:138)
	at com.google.devtools.j2objc.gen.StatementGenerator.printMethodInvocationNameAndArgs(StatementGenerator.java:152)
	at com.google.devtools.j2objc.gen.StatementGenerator.visit(StatementGenerator.java:572)
	at com.google.devtools.j2objc.ast.MethodInvocation.acceptInner(MethodInvocation.java:118)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.gen.StatementGenerator.visit(StatementGenerator.java:412)
	at com.google.devtools.j2objc.ast.ExpressionStatement.acceptInner(ExpressionStatement.java:51)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.gen.StatementGenerator.printStatements(StatementGenerator.java:256)
	at com.google.devtools.j2objc.gen.StatementGenerator.visit(StatementGenerator.java:245)
	at com.google.devtools.j2objc.ast.Block.acceptInner(Block.java:54)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)
	at com.google.devtools.j2objc.gen.StatementGenerator.generate(StatementGenerator.java:127)
	at com.google.devtools.j2objc.gen.TypeImplementationGenerator.generateStatement(TypeImplementationGenerator.java:344)
	at com.google.devtools.j2objc.gen.TypeImplementationGenerator.printMethodDeclaration(TypeImplementationGenerator.java:245)
	at com.google.devtools.j2objc.gen.TypeGenerator.printDeclaration(TypeGenerator.java:164)
	at com.google.devtools.j2objc.gen.TypeGenerator.printDeclarations(TypeGenerator.java:176)
	at com.google.devtools.j2objc.gen.TypeGenerator.printInnerDeclarations(TypeGenerator.java:218)
	at com.google.devtools.j2objc.gen.TypeImplementationGenerator.generate(TypeImplementationGenerator.java:87)
	at com.google.devtools.j2objc.gen.TypeImplementationGenerator.generate(TypeImplementationGenerator.java:71)
	at com.google.devtools.j2objc.gen.GeneratedType.fromTypeDeclaration(GeneratedType.java:117)
	at com.google.devtools.j2objc.gen.GenerationUnit.addCompilationUnit(GenerationUnit.java:178)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:107)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:158)
	at com.google.devtools.j2objc.pipeline.FileProcessor.access$0(FileProcessor.java:151)
	at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:136)
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:175)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:141)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:70)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:1)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:177)

```
The translator is build from the latest source, and when I debug in, the stacktrace is 

``` java
private TreeNode copyConstantValue(JCTree node, Expression newNode) {
    Object value = node.type.constValue();
    if (value instanceof Integer) {
      switch (node.type.baseType().getKind()) {
        case BOOLEAN:
          // Convert boolean values of 1/0 as true/false.
          value = ((Integer) value).intValue() == 1;
          break;
        case CHAR:
          value = (char) ((Integer) value).intValue();
          break;
        default:  // value doesn't need to be changed.
      }
    }
    return newNode.setConstantValue(value);
  }
```
Problem is node.type.constValue() expression return null.

I think the method of class TreeConverter
``` java
private TreeNode convert(Object obj) {
    if (obj == null) {
      return null;
    }
    JCTree node = (JCTree) obj;
    TreeNode newNode = convertInner(node)
        .setPosition(getPosition(node));
    if (newNode instanceof Expression) {
      copyConstantValue(node, (Expression) newNode);
    }
    return newNode;
  }
```
StringLiteral no need copyConstantValue and add condition 
if (newNode instanceof Expression && !(newNode instanceof StringLiteral))

**Comment by tomball** [comment]
It looks like javac has a string literal without any literal value, since TreeConverter.convertStringLiteral() doesn't check the javac values. What does "javac -version" return on your system? I cannot duplicate this error on my system, which has "javac 1.8.0_131".

**Comment by kingxt** [comment]
``` sheel
Last login: Thu Aug 24 10:43:45 on ttys000
➜  ~ javac -version
javac 1.8.0_25
➜  ~ 
```

**Comment by tomball** [comment]
Thanks for the update. Your version of javac is ancient (by Java standards :-)), as we're running 1.8.0_131. I encourage you to update to the latest JDK ([download it here](http://www.oracle.com/technetwork/java/javase/downloads/index.html)). Hmm, it's up to version 144, so I'll be updating, too.

I added a null-check in copyConstantValue(), and will test it with 1.8.0_25.

**Comment by kingxt** [comment]
OK，thanks very much. I will try with the newest java sdk.

**Comment by tomball** [comment]
Should be fixed in current source -- please reopen with a test if you still have an issue.
