### ISSUE TITLE
With Java9, j2objc fails with a NoClassDefFoundError for sun.misc.URLClassPath

### ISSUE THREAD

**Issue by simonharrer** [google/j2objc#886]
With JAVA_HOME pointing to JDK9, the translation process with `j2objc` fails with a NoClassDefFoundError for `sun/misc/URLClassPath` which is apparently no longer within the JRE/JDK.

Stacktrace:
```
com.google.devtools.j2objc.ast.TreeVisitorError: /Example.java:20: internal error translating "/Example.java"

error: NoClassDefFoundError: sun/misc/URLClassPath

at com.strobel.assembler.metadata.ClasspathTypeLoader.<init>(ClasspathTypeLoader.java:66)

at com.strobel.assembler.metadata.ClasspathTypeLoader.<init>(ClasspathTypeLoader.java:42)

at com.strobel.assembler.metadata.MetadataSystem.<init>(MetadataSystem.java:48)

at com.strobel.assembler.metadata.MetadataSystem.instance(MetadataSystem.java:40)

at com.strobel.assembler.metadata.PrimitiveType.<init>(PrimitiveType.java:28)

at com.strobel.assembler.metadata.BuiltinTypes.<clinit>(BuiltinTypes.java:40)

at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)

at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1023)

at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:699)

at com.strobel.compilerservices.RuntimeHelpers.ensureClassInitialized(RuntimeHelpers.java:31)

at com.strobel.assembler.metadata.MetadataSystem.<clinit>(MetadataSystem.java:147)

at com.google.devtools.j2objc.util.ClassFile.create(ClassFile.java:64)

at com.google.devtools.j2objc.util.PackageInfoLookup.parseDataFromClassFile(PackageInfoLookup.java:198)

at com.google.devtools.j2objc.util.PackageInfoLookup.findPackageData(PackageInfoLookup.java:120)

at com.google.devtools.j2objc.util.PackageInfoLookup.getPackageData(PackageInfoLookup.java:103)

at com.google.devtools.j2objc.util.PackageInfoLookup.getObjectiveCName(PackageInfoLookup.java:89)

at com.google.devtools.j2objc.util.PackagePrefixes.getPrefix(PackagePrefixes.java:117)

at com.google.devtools.j2objc.util.NameTable.getPrefix(NameTable.java:674)

at com.google.devtools.j2objc.util.NameTable.getFullNameImpl(NameTable.java:646)

at com.google.devtools.j2objc.util.NameTable.getFullName(NameTable.java:614)

at com.google.devtools.j2objc.translate.MetadataWriter.getTypeName(MetadataWriter.java:434)

at com.google.devtools.j2objc.translate.MetadataWriter.getTypeName(MetadataWriter.java:425)

at com.google.devtools.j2objc.translate.MetadataWriter.access$1100(MetadataWriter.java:63)

at com.google.devtools.j2objc.translate.MetadataWriter$MetadataGenerator.getMethodMetadata(MetadataWriter.java:246)

at com.google.devtools.j2objc.translate.MetadataWriter$MetadataGenerator.generateMethodsMetadata(MetadataWriter.java:196)

at com.google.devtools.j2objc.translate.MetadataWriter$MetadataGenerator.generateClassMetadata(MetadataWriter.java:137)

at com.google.devtools.j2objc.translate.MetadataWriter$MetadataGenerator.access$100(MetadataWriter.java:118)

at com.google.devtools.j2objc.translate.MetadataWriter.visitType(MetadataWriter.java:110)

at com.google.devtools.j2objc.translate.MetadataWriter.endVisit(MetadataWriter.java:82)

at com.google.devtools.j2objc.ast.TypeDeclaration.acceptInner(TypeDeclaration.java:100)

at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)

at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)

at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:90)

at com.google.devtools.j2objc.ast.CompilationUnit.acceptInner(CompilationUnit.java:181)

at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:95)

at com.google.devtools.j2objc.ast.UnitTreeVisitor.run(UnitTreeVisitor.java:50)

at com.google.devtools.j2objc.pipeline.TranslationProcessor.applyMutations(TranslationProcessor.java:244)

at com.google.devtools.j2objc.pipeline.TranslationProcessor.processConvertedTree(TranslationProcessor.java:102)

at com.google.devtools.j2objc.pipeline.FileProcessor.processCompiledSource(FileProcessor.java:158)

at com.google.devtools.j2objc.pipeline.FileProcessor.access$000(FileProcessor.java:39)

at com.google.devtools.j2objc.pipeline.FileProcessor$1.handleParsedUnit(FileProcessor.java:136)

at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:175)

at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:141)

at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:70)

at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:78)

at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)

at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:177)

Caused by: java.lang.ClassNotFoundException: sun.misc.URLClassPath

at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)

at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)

... 47 more

```

**Comment by tomball** [comment]
It looks like the Procyon library we're using isn't Java 9 compatible. Good thing it's open-source, so I can send that team a patch.

**Comment by tomball** [comment]
Looks like Procyon's source [was updated two days ago](https://bitbucket.org/mstrobel/procyon/commits/7f19d10346b177e9cf754f04e7a1cdb3fd97e136). As soon as a new version is available from Maven, I'll update our build to use it.

**Comment by tomball** [comment]
This fix updates the j2objc command and its build to always use the latest Java 8 installation on a system, regardless of whether Java 9 is the default version.
